# Generated by Django 5.2.5 on 2025-08-23 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_level', models.CharField(choices=[('HARD', 'Hard'), ('SOFT', 'Soft')], max_length=10)),
                ('weight', models.IntegerField(default=0, help_text="Penalty weight if the constraint is 'Soft'")),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text="Code name for the constraint, e.g., 'TEACHER_UNAVAILABLE'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text="e.g., 'Room 204', 'Chemistry Lab'", max_length=100)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text="e.g., 'Grade 9A', 'AP History'", max_length=100)),
                ('grade_level', models.CharField(help_text="e.g., 'Balvatika', '1', '12'", max_length=20)),
                ('student_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(help_text="e.g., 'PPRT', 'PRT', 'TGT', 'PGT'", max_length=50)),
                ('max_periods_per_week', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_key', models.CharField(help_text="e.g., 'teacher_id', 'timeslot_id'", max_length=50)),
                ('parameter_value', models.CharField(max_length=255)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.constraintinstance')),
            ],
        ),
        migrations.AddField(
            model_name='constraintinstance',
            name='constraint_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.constrainttype'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveIntegerField()),
                ('is_double_period', models.BooleanField(default=False)),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teachers', models.ManyToManyField(help_text='Select one or more teachers for this lesson', to='core.teacher')),
            ],
        ),
    ]
