# Generated by Django 5.2.5 on 2025-08-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='student_count',
        ),
    ]
