# Generated by Django 5.2.5 on 2025-08-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_room_remove_studentgroup_student_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmSettings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.BooleanField(default=False)),
            ],
        ),
    ]
