# Generated by Django 5.2.5 on 2025-08-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_algorithmsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlgorithmSettings',
        ),
    ]
