# Generated by Django 5.2.5 on 2025-08-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_algorithmsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_double_period',
        ),
    ]
