# Generated by Django 5.2.5 on 2025-08-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lesson_is_double_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
    ]
